
services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/certs:/etc/letsencrypt/live:ro
      - ./certbot/www:/var/www/certbot:rw
      - nginx-cache:/var/cache/nginx
    depends_on:
      - frontend
      - backend
    restart: always
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./nginx/certs:/etc/letsencrypt/live
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 12h & wait $${!}; certbot renew --webroot -w /var/www/certbot --post-hook \"nginx -s reload\"; done'"
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    build:
      context: ./raku-frontend
      dockerfile: Dockerfile.prod
    container_name: frontend
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=https://admin.rakujlpt.com/api/v1
    expose:
      - "3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/_next/static" ]
      interval: 20s
      timeout: 5s
      retries: 3
      start_period: 20s
    restart: on-failure
    networks:
      - app-network

  backend:
    build:
      context: ./raku-backend
      dockerfile: Dockerfile.prod
    container_name: backend
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_HOST=db
      - DB_DATABASE=raku_db
      - DB_USERNAME=raku
      - DB_PASSWORD=12345
    expose:
      - "9000"
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 3
      start_period: 20s
    restart: on-failure
    networks:
      - app-network
    volumes:
      - backend-storage:/var/www/backend

  queue:
    build:
      context: ./raku-backend
      dockerfile: Dockerfile.prod
    container_name: queue
    command: php /var/www/backend/artisan queue:work --sleep=3 --tries=3 --timeout=90
    environment:
      - QUEUE_CONNECTION=database
    depends_on:
      - db
      - backend
    restart: on-failure
    networks:
      - app-network
    volumes:
      - backend-storage:/var/www/backend

  db:
    image: mysql:8
    container_name: mysql-db2
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: raku_db
      MYSQL_USER: raku
      MYSQL_PASSWORD: 12345
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
    networks:
      - app-network

volumes:
  dbdata:
  nginx-cache:
  backend-storage:

networks:
  app-network:
    driver: bridge
